import {goldRewardEligibility,readGoldBlood} from './goldDominance';
export const SILVER_ELEMENTS=['火','水','土','风','光','暗','空间'] as const;
export const SILVER_SKILLS=['元素潮汐','元素掌控','元素融合','元素之杖','元素风暴','空间传送·禁锢','银龙王真身','七元素·大裂变','创造与毁灭'];
export const SILVER_BODY=[
 {id:'body',name:'龙躯',desc:'每阶气血、防御+2%；元素之杖提供护盾，护盾总量不超过6%气血'},
 {id:'spirit',name:'精神之海',desc:'每阶精神+2%；空间禁锢概率提升5%，最多40%'},
 {id:'heart',name:'元素之心',desc:'每阶魂力上限+3%，银龙王魂技消耗降低2%'},
 {id:'space',name:'空间掌控',desc:'每阶速度+2%，银龙王攻击魂技忽略5%防御'},
] as const;
const nat=(v:any)=>Number.isFinite(v)?Math.max(0,Math.floor(v)):0;
export function hasSilverKing(p:any){return p?.martialSoul?.name==='银龙王'||(p?.isTwinSoul===true&&p?.secondSoul?.name==='银龙王');}
export function readSilverBlood(v:any){return {version:1,elements:Object.fromEntries(SILVER_ELEMENTS.map(e=>[e,Math.min(4,nat(v?.elements?.[e]))])),body:Object.fromEntries(SILVER_BODY.map(e=>[e.id,Math.min(4,nat(v?.body?.[e.id]))])),insight:readGoldBlood(v?.insight)};}
export function silverRanks(p:any){const v=readSilverBlood(p?.silverBloodline),cap=[60,99,139,169].filter(l=>(p?.level||0)>=l&&(l<139||p?.divineTrial?.inherited)).length;if(!hasSilverKing(p))return {...v,elements:Object.fromEntries(SILVER_ELEMENTS.map(e=>[e,0])),body:Object.fromEntries(SILVER_BODY.map(e=>[e.id,0]))};return {...v,elements:Object.fromEntries(SILVER_ELEMENTS.map(e=>[e,Math.min(v.elements[e],cap)])),body:Object.fromEntries(SILVER_BODY.map(e=>[e.id,Math.min(v.body[e.id],cap)]))};}
export function silverBonuses(p:any){const r=silverRanks(p),steps=hasSilverKing(p)?Math.floor(r.insight.points/100):0;return {hp:r.body.body*.02,defense:r.body.body*.02,spirit:r.body.spirit*.02+steps*.01,mana:r.body.heart*.03+steps*.005,speed:r.body.space*.02,penetration:r.body.space*.05,cost:r.body.heart*.02,skill:Object.values(r.elements).reduce((n,x)=>n+x,0)*.005};}
export function silverDomain(p:any){const n=Object.values(silverRanks(p).elements).filter(x=>x>0).length;return n>=7?{damage:.2,cost:.1}:n>=5?{damage:.15,cost:.08}:n>=3?{damage:.1,cost:.05}:null;}
export function silverRequirement(p:any,kind:'elements'|'body',id:string){const v=readSilverBlood(p?.silverBloodline),rank=v[kind][id],level=[60,99,139,169][rank]||169,essence=(rank+1)*150,marrow=(rank+1)*30,core=rank+1,bag=p?.dragonBloodline||{};const reason=!hasSilverKing(p)?'需要银龙王武魂':rank===undefined?'无效进化路线':rank>=4?'已达最高阶':p?.dragonValley?.trial||p?.dragonValley?.exploration?'请先结束龙谷试炼':(p?.level||0)<level?level+'级解锁':rank>=2&&!p?.divineTrial?.inherited?'需继承神位':(bag.essence||0)<essence||(bag.marrow||0)<marrow||(bag.core||0)<core?'龙谷材料不足':'';return {rank,level,essence,marrow,core,reason};}
export function silverUpgrade(p:any,kind:'elements'|'body',id:string,expectedRank?:number){const req=silverRequirement(p,kind,id);if(expectedRank!==undefined&&req.rank!==expectedRank)return {player:p,reason:'进度已变化，请重新查看升级预览'};if(req.reason)return {player:p,reason:req.reason};const v=readSilverBlood(p.silverBloodline),b=p.dragonBloodline;return {reason:'',player:{...p,dragonBloodline:{...b,essence:b.essence-req.essence,marrow:b.marrow-req.marrow,core:b.core-req.core},silverBloodline:{...v,[kind]:{...v[kind],[id]:req.rank+1}}}};}
export function reincarnateSilver(p:any){return {...readSilverBlood(null),insight:readSilverBlood(p?.silverBloodline).insight};}
export function silverSkill(p:any,slot:number,index=0){const soul=index===1?(p?.isTwinSoul===true?p.secondSoul:null):p?.martialSoul;if(soul?.name!=='银龙王'||slot<0||slot>8)return null;const desc=[
 '精神+15%，持续3次行动；本次不追加攻击。','精神、防御+20%，持续2次行动；本次不追加攻击。','融合元素造成伤害×1.15。','凝聚元素之杖，获得最多6%气血护盾并净化；本次不追加攻击。','元素风暴伤害×1.2，附加2次持续伤害，单次不超过敌方最大气血3%。','空间禁锢造成伤害，20%至40%概率跳过敌方1次行动，冷却3次行动。','沿用武魂真身开关。','七元素大裂变，伤害×1.4。','创造与毁灭，伤害×1.5；自身存活时恢复最多3%最大气血，冷却3次行动。'];
 const source=slot<4?'原著明确魂技名；数值为游戏平衡':slot===6?'原著形态；游戏第七魂技适配':slot===8?'《终极斗罗》关联能力，游戏改编，非已核实第九魂技名':'原著能力，名称与魂技位置为游戏改编';
 return {name:SILVER_SKILLS[slot],desc:desc[slot]+' '+source,source,skillType:[0,1,3,6].includes(slot)?'buff':'attack',cooldown:[5,8].includes(slot)?3:0,key:'silver:'+index+':'+slot};}
export function normalizeSilver(p:any){if(!p)return p;let out={...p,silverBloodline:readSilverBlood(p.silverBloodline)};for(const [skey,rkey,index] of [['martialSoul','soulRings',0],['secondSoul','secondSoulRings',1]] as const){if((index===1&&p.isTwinSoul!==true)||p[skey]?.name!=='银龙王')continue;out[skey]={...p[skey],element:'全属性',extremeAttribute:'全属性',cultivationAttr:'spirit',soulSkills:[...SILVER_SKILLS]};out[rkey]=(p[rkey]||[]).map((r:any,i:number)=>{const s=silverSkill(out,i,index);return s?{...r,skillName:s.name,skillDesc:s.desc,skillType:s.skillType}:r;});}return out;}
export function createSilverBattle(p:any,config:any,id:string){if(!hasSilverKing(p))return;const d=silverDomain(p),reward=goldRewardEligibility({...p,martialSoul:{name:'金龙王'}},config).reward;return {version:1,id,turns:d?3:0,damage:d?.damage||0,cost:d?.cost||0,reward,settled:false};}
export function readSilverBattle(v:any){if(v?.version!==1||typeof v.id!=='string'||!v.id||v.id.length>=100)return;return {...v,turns:Math.min(4,nat(v.turns)),damage:[.1,.15,.2].includes(v.damage)?v.damage:0,cost:[.05,.08,.1].includes(v.cost)?v.cost:0,reward:[1,3,10].includes(v.reward)?v.reward:0,settled:v.settled===true};}
export function settleSilver(p:any,b:any,phase:string){if(!hasSilverKing(p)||phase!=='victory'||!b||b.settled||!b.reward)return p;const v=readSilverBlood(p.silverBloodline),old=v.insight;if(old.points>=2000||old.claimed.includes(b.id))return p;return {...p,silverBloodline:{...v,insight:{...old,points:Math.min(2000,old.points+b.reward),claimed:[...old.claimed,b.id]}}};}
export function syncSilverDomain(s:any,b:any){if(!s)return;delete s.actors.player.effects.silverRealm;if(!b?.turns||s.actors.player.hp<=0||s.actors.enemy.hp<=0)return;s.actors.player.effects.silverRealm={id:'silverRealm',type:'silverSkillUp',value:b.damage,turns:b.turns,born:s.actors.player.action,manual:true,label:'银龙元素领域',negative:false};}
export function silverCost(p:any,b:any,cost:number,index:number){if(!silverSkill(p,0,index))return cost;return Math.max(1,Math.ceil(cost*(1-Math.min(.5,silverBonuses(p).cost+(b?.turns?b.cost:0)))-1e-9));}
