import {useState,useRef} from 'react';
import {useGame} from '@/lib/gameStore';
import {dragonProgress,dragonAction,ARMOR_PARTS,TRIALS,EVOLUTIONS,armorTier,armorBonuses,spiritEvolution} from '@/lib/dragonLegend';
import {toast} from 'sonner';
const card={background:'rgba(17,30,45,.85)',border:'1px solid #36516b',borderRadius:16,padding:20,marginBottom:16};
const button={background:'#433080',color:'#fff',border:'1px solid #7965bb',borderRadius:10,padding:'10px 16px',cursor:'pointer',minHeight:44};
export default function DragonLegendPanel({mode}:{mode:'ascension'|'forge'}){
 const {player,attributes,setPlayer,inBattle,setBattleState,setInBattle}=useGame();
 const [selected,setSelected]=useState(''),[name,setName]=useState(''),[style,setStyle]=useState('attack');const gate=useRef(false);
 if(!player||!attributes)return null;const d=dragonProgress(player),tier=armorTier(player),spirit=player.soulSpirits?.find(s=>s.spiritId===(selected||player.soulSpirits?.[0]?.spiritId)),stage=spiritEvolution(spirit),target=EVOLUTIONS[stage];
 function act(a:any){if(inBattle)return toast.error('战斗中不能操作');const now=Date.now(),preview=dragonAction(player,a,now);if(preview.reason)return toast.error(preview.reason);setPlayer(p=>dragonAction(p,a,now).player);toast.success(preview.message);}
 function enter(i:number){if(gate.current||inBattle)return;gate.current=true;const id=crypto.randomUUID(),now=Date.now(),action={type:'enter',tier:i,id},r=dragonAction(player,action,now);if(r.reason){gate.current=false;return toast.error(r.reason);}const t=TRIALS[i];setPlayer(p=>dragonAction(p,action,now).player);setBattleState({battleType:'challenge',locationId:'ascension-platform',enemy:{id:'ascension-'+id,name:t.name+'·守卫',years:1000*(i+1),hp:Math.max(100,Math.round(attributes.hp*t.scale)),maxHp:Math.max(100,Math.round(attributes.hp*t.scale)),attack:Math.max(1,Math.round(attributes.attack*t.scale*.35)),defense:Math.max(1,Math.round(attributes.defense*t.scale*.25)),speed:Math.max(1,Math.round(attributes.speed*t.scale*.7)),spirit:Math.max(1,Math.round(attributes.spirit*t.scale*.35)),element:spirit?.attribute||'精神属性',skillName:'灵力冲击',skillDesc:'升灵台虚拟守卫的冲击'},phase:'playerTurn',logs:[],updatedAt:now,meta:{ascension:{id,tier:i,reward:t.reward}}} as any);setInBattle(true);}
 const fmt=(n:number)=>n.toLocaleString();
 return <section style={{maxWidth:950,margin:'0 auto',color:'#e4eef9',padding:16}} data-dragon-legend={mode}>
 <h2 style={{fontSize:26,fontWeight:700,marginBottom:16}}>{mode==='ascension'?'升灵台':'锻造协会 · 斗铠工坊'}</h2>
 {mode==='ascension'?<>
 <div style={card}><h3>灵力储备：{fmt(d.lingli)}</h3>{d.trial&&!d.trial.claimed&&<button style={button} onClick={()=>act({type:"leave",id:d.trial.id})}>放弃未结束的试炼</button>}<p>挑战虚拟魂兽获取灵力，用于进化已契约的普通魂灵。试炼不掉落魂环、魂骨；失败或逃跑不返还入场消耗。</p></div>
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12}}>{TRIALS.map((t,i)=><div key={t.name} style={card}><h3>{t.name}</h3><p>{t.level}级解锁 · 胜利灵力 +{t.reward}</p><p>入场：{t.stamina}体力 / {fmt(t.coins)}魂币</p><button style={button} disabled={player.level<t.level||!spirit} onClick={()=>enter(i)}>挑战{t.name}</button></div>)}</div>
 <div style={card}><h3>魂灵进化</h3><select aria-label="培养魂灵" value={spirit?.spiritId||''} onChange={e=>setSelected(e.target.value)} style={{...button,width:'100%',margin:'12px 0'}}><option value="">选择已契约魂灵</option>{player.soulSpirits?.map(s=><option key={s.spiritId} value={s.spiritId}>{s.name}</option>)}</select>
 {spirit?<><p>{spirit.name} · {stage?EVOLUTIONS[stage-1].name:'未升灵'} · 额外战斗属性 +{stage*10}%</p><p>进化提高魂灵自身攻击、防御、速度、气血及上阵贡献；保留原属性和境界，不改变已吸收魂环。</p><button style={button} disabled={!target||d.lingli<(target?.cost||0)} onClick={()=>act({type:'evolve',id:spirit.spiritId})}>{target?`进化为${target.name} · ${fmt(target.cost)}灵力`:'已达百万年上限'}</button></>:<p>先在魂灵页面契约一个普通魂灵。</p>}</div>
 </>:<>
 <div style={card}><h3>锻造经验：{fmt(d.forgeExp)} · {d.forgeExp>=100?'灵锻已解锁':'100经验解锁灵锻'}</h3><p>沉银矿石 {d.ore} / 千锻沉银 {d.thousand} / 灵锻沉银 {d.spiritual}</p><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><button style={button} onClick={()=>act({type:'mine'})}>采矿 ×5 · 20体力 / 200魂币</button><button style={button} onClick={()=>act({type:'forge',tier:1})}>千锻 · 5矿石 / 500魂币</button><button style={button} onClick={()=>act({type:'forge',tier:2})}>灵锻 · 10矿石 / 2,000魂币</button></div><p>本期锻造必定成功。每次千锻经验+10，灵锻经验+25。</p></div>
 <div style={card}><h3>斗铠部件 · {d.parts.filter(x=>x>0).length}/11</h3><p>一字：50级＋主修5环；每件消耗2千锻沉银、3,000魂币。二字：60级＋主修6环；每件晋升消耗2灵锻沉银、10,000魂币。</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:10}}>{ARMOR_PARTS.map((part,i)=><div key={part} style={{border:'1px solid #43536b',padding:12,borderRadius:10}}><p>{part} · {['未制作','一字','二字'][d.parts[i]]}</p><button style={button} disabled={d.parts[i]>=2} onClick={()=>act({type:'craft',part:i})}>{d.parts[i]===0?'制作':d.parts[i]===1?'晋升二字':'已达二字'}</button></div>)}</div></div>
 <div style={card}><h3>{tier?`${['','一字','二字'][tier]}斗铠`:'未成套'} · {d.name||'尚未命名'} · {d.equipped?'已装备':'未装备'}</h3><p>每一字部件增加五维0.3%；成套后所选方向每阶额外+5%，二字按主修属性契合额外+3%（金火雷→攻击、冰水土→防御、风→速度、光暗精神→精神、木生命→气血）。</p><p>当前加成：{Object.entries(armorBonuses(player)).map(([k,v])=>`${({attack:'攻击',defense:'防御',speed:'速度',spirit:'精神',hp:'气血'})[k]} +${(v*100).toFixed(1)}%`).join(' / ')}</p><button style={button} onClick={()=>act({type:'equip'})}>{d.equipped?'卸下斗铠':'装备斗铠'}</button><div style={{display:'flex',flexWrap:'wrap',gap:10,marginTop:12}}><input aria-label="斗铠名称" placeholder={`输入${tier||1}字斗铠名称`} value={name} maxLength={2} onChange={e=>setName(e.target.value)} style={button}/><select aria-label="斗铠方向" value={style} onChange={e=>setStyle(e.target.value)} style={button}><option value="attack">攻击</option><option value="defense">防御</option><option value="control">控制</option><option value="support">辅助</option></select><button style={button} onClick={()=>act({type:'configure',name,style})}>保存名称与方向</button></div><p>二字成套解锁“斗铠振奋”：每场一次，消耗最大魂力10%，恢复最大气血3%，占用一次行动。</p></div>
 </>}
 <p style={{color:'#a7b7cb'}}>转世保留锻造经验，重置灵力、材料、斗铠与魂灵进化。三、四字斗铠及领域将在后续开放。</p>
 </section>;
}
