import {valleyReward} from '@/lib/dragonBloodline';
import {materialText} from '@/lib/dragonMaterials';
import {useRef,useEffect} from 'react';
import {useGame} from '@/lib/gameStore';import {toast} from 'sonner';import {dragonStyles} from './DragonLegendPanel';
import {VALLEY_ZONES,VALLEY_NODES,valleyProgress,valleyAction,valleyRequirements,valleyEnemy,bloodlineProgress} from '@/lib/dragonBloodline';
export default function DragonValleyPanel({onBack}:{onBack:()=>void}){const {player,inBattle,setPlayer,startBattle}=useGame(),gate=useRef(false);useEffect(()=>{if(!inBattle)gate.current=false;},[inBattle]);if(!player)return null;const d=valleyProgress(player),b=bloodlineProgress(player);
 function act(a:any){if(inBattle)return;const now=Date.now(),r=valleyAction(player,a,now);if(r.reason)return toast.error(r.reason);setPlayer(p=>valleyAction(p,a,now).player);toast.success(r.message);}
 function fight(){if(inBattle||gate.current)return;gate.current=true;const id=d.exploration?.id,a={type:'enter',id},r=valleyAction(player,a);if(r.reason){gate.current=false;return toast.error(r.reason);}const t=r.player.dragonValley.trial;setPlayer(p=>valleyAction(p,a).player);startBattle({battleType:'challenge',locationId:'dragon-valley',enemy:valleyEnemy(t.node,t.seal),meta:{valley:{...t}}} as any);}
 return <section className="dragon-ui" data-dragon-valley><style>{dragonStyles}</style><div className="dragon-summary"><button className="dragon-quiet" onClick={onBack}>← 返回地图</button><span className="dragon-pill">精华 {b.essence} · 龙髓 {b.marrow} · 龙核 {b.core}</span></div><div className="dragon-card"><h3>龙谷 · 龙魂遗迹</h3><p className="dragon-muted">探索遗迹 → 选择事件 → 挑战守卫。首通额外精华只领取一次，重复挑战仍获得基础材料。</p><p className="dragon-hint">转世保留图鉴与首通记录，材料及封印进度重置；不消耗武魂位置，不掉落魂环或魂骨。</p></div>
 {d.exploration&&<div className="dragon-card"><h3>当前探索</h3>{d.exploration.stage==='choice'?<div className="dragon-grid forge"><button className="dragon-secondary" onClick={()=>act({type:'choice',id:d.exploration.id,choice:'gather'})}>采集精华 ×2</button><button className="dragon-secondary" onClick={()=>act({type:'choice',id:d.exploration.id,choice:'recover'})}>恢复体力20</button></div>:d.exploration.stage==='ready'?<button className="dragon-primary" disabled={inBattle} onClick={()=>fight()}>挑战遗迹守卫</button>:<p>等待战斗结束</p>}<button className="dragon-quiet" disabled={inBattle} onClick={()=>act({type:'leave',id:d.exploration.id})}>放弃本次探索</button></div>}
 {d.trial&&!d.exploration&&<div className="dragon-warning">存在未结束的试炼<button className="dragon-quiet" onClick={()=>act({type:'leave',id:d.trial.id})}>结束当前试炼</button></div>}
 {VALLEY_ZONES.map((z,i)=><div className="dragon-card" key={z.name}><div className="dragon-section-title"><span>{z.name}</span><span className="dragon-muted">{z.level}级{ i>0?' · 继承神位':''}</span></div><p className="dragon-muted">{z.desc}</p><div className="dragon-grid forge">{VALLEY_NODES.filter(n=>n.zone===i).map(n=>{const reason=valleyRequirements(player,n.id);return <div className="dragon-card" key={n.id}><h4>{n.name}</h4><p className="dragon-hint">{n.mechanic} · 体力 {40*(i+1)} · 魂币 {500*(i+1)}</p><p className="dragon-hint">胜利必得：{materialText(valleyReward(n.id,false))}</p>{!d.cleared.includes(n.id)&&<p className="dragon-green">首次通关额外精华 +10</p>}<p className="dragon-hint">用于封印、金银真身、元素掌控与金银共鸣；探索采集另获精华 +2。无概率掉落，失败或逃跑无胜利奖励。</p><button className="dragon-primary" disabled={!!reason||inBattle||!!d.exploration||!!d.trial} onClick={()=>act({type:'explore',node:n.id,id:crypto.randomUUID()})} aria-label={'探索'+n.name}>{reason||'探索遗迹'}</button>{d.cleared.includes(n.id)&&<p className="dragon-green">已通关</p>}</div>})}</div></div>)}

 <div className="dragon-card"><button className="dragon-secondary" disabled={inBattle||!!d.trial||!!d.exploration||(player.abyssFrontier?.merit||0)<60} onClick={()=>act({type:'exchange'})}>60军功 → 龙魂精华 ×5</button><p className="dragon-hint">龙谷图鉴：{d.codex.length}/9</p></div></section>;
}
