import {useRef,useEffect} from 'react';
import {useGame} from '@/lib/gameStore';import {toast} from 'sonner';import {dragonStyles} from './DragonLegendPanel';
import {VALLEY_ZONES,VALLEY_NODES,valleyProgress,valleyAction,valleyRequirements,valleyEnemy,bloodlineProgress,sealRequirements,BLOOD_SKILLS} from '@/lib/dragonBloodline';
export default function DragonValleyPanel({onBack}:{onBack:()=>void}){const {player,inBattle,setPlayer,startBattle}=useGame(),gate=useRef(false);useEffect(()=>{if(!inBattle)gate.current=false;},[inBattle]);if(!player)return null;const d=valleyProgress(player),b=bloodlineProgress(player),req=sealRequirements(player);
 function act(a:any){if(inBattle)return;const now=Date.now(),r=valleyAction(player,a,now);if(r.reason)return toast.error(r.reason);setPlayer(p=>valleyAction(p,a,now).player);toast.success(r.message);}
 function fight(seal=false){if(inBattle||gate.current)return;gate.current=true;const id=seal?crypto.randomUUID():d.exploration?.id,a={type:seal?'seal':'enter',id},r=valleyAction(player,a);if(r.reason){gate.current=false;return toast.error(r.reason);}const t=r.player.dragonValley.trial;setPlayer(p=>valleyAction(p,a).player);startBattle({battleType:'challenge',locationId:'dragon-valley',enemy:valleyEnemy(t.node,t.seal),meta:{valley:{...t}}} as any);}
 return <section className="dragon-ui" data-dragon-valley><style>{dragonStyles}</style><div className="dragon-summary"><button className="dragon-quiet" onClick={onBack}>← 返回地图</button><span className="dragon-pill">精华 {b.essence} · 龙髓 {b.marrow} · 龙核 {b.core}</span></div><div className="dragon-card"><h3>龙谷 · 龙魂遗迹</h3><p className="dragon-muted">探索遗迹 → 选择事件 → 挑战守卫。首通额外精华只领取一次，重复挑战仍获得基础材料。</p><p className="dragon-hint">转世保留图鉴与首通记录，材料及封印进度重置；不消耗武魂位置，不掉落魂环或魂骨。</p></div>
 {d.exploration&&<div className="dragon-card"><h3>当前探索</h3>{d.exploration.stage==='choice'?<div className="dragon-grid forge"><button className="dragon-secondary" onClick={()=>act({type:'choice',id:d.exploration.id,choice:'gather'})}>采集精华 ×2</button><button className="dragon-secondary" onClick={()=>act({type:'choice',id:d.exploration.id,choice:'recover'})}>恢复体力20</button></div>:d.exploration.stage==='ready'?<button className="dragon-primary" disabled={inBattle} onClick={()=>fight()}>挑战遗迹守卫</button>:<p>等待战斗结束</p>}<button className="dragon-quiet" disabled={inBattle} onClick={()=>act({type:'leave',id:d.exploration.id})}>放弃本次探索</button></div>}
 {d.trial&&!d.exploration&&<div className="dragon-warning">存在未结束的封印试炼<button className="dragon-quiet" onClick={()=>act({type:'leave',id:d.trial.id})}>放弃封印试炼</button></div>}
 {VALLEY_ZONES.map((z,i)=><div className="dragon-card" key={z.name}><div className="dragon-section-title"><span>{z.name}</span><span className="dragon-muted">{z.level}级{ i>0?' · 继承神位':''}</span></div><p className="dragon-muted">{z.desc}</p><div className="dragon-grid forge">{VALLEY_NODES.filter(n=>n.zone===i).map(n=>{const reason=valleyRequirements(player,n.id);return <div className="dragon-card" key={n.id}><h4>{n.name}</h4><p className="dragon-hint">{n.mechanic} · 体力 {40*(i+1)} · 魂币 {500*(i+1)}</p><button className="dragon-primary" disabled={!!reason||inBattle||!!d.exploration||!!d.trial} onClick={()=>act({type:'explore',node:n.id,id:crypto.randomUUID()})} aria-label={'探索'+n.name}>{reason||'探索遗迹'}</button>{d.cleared.includes(n.id)&&<p className="dragon-green">已通关</p>}</div>})}</div></div>)}
 <div className="dragon-card" data-bloodline><h3>{b.unlocked?'金龙王血脉 · 十八道封印':'封印中的血脉'}</h3>{!b.unlocked?<p className="dragon-muted">彩蛋尚未解锁。解锁条件待定，暂不开放。</p>:<><p>已解开 {b.seals}/18 · 攻击 +{b.seals}% · 气血 +{(b.seals*1.5).toFixed(1)}%</p><p className="dragon-hint">下一封印：{req.level}级 · 精华 {req.essence} · 龙髓 {req.marrow} · 龙核 {req.core}。胜利才扣材料；失败不解封、不扣材料。</p><button className="dragon-primary" disabled={!!req.reason||!!d.trial||!!d.exploration||inBattle} onClick={()=>fight(true)}>{req.reason||'挑战第'+req.next+'道封印'}</button>{BLOOD_SKILLS.map(s=><p className="dragon-hint" key={s.id}>{s.seal}封印 · {s.name}：{s.desc}{b.seals>=s.seal?' · 已解锁':''}</p>)}</>}</div>
 <div className="dragon-card"><button className="dragon-secondary" disabled={inBattle||!!d.trial||!!d.exploration||(player.abyssFrontier?.merit||0)<60} onClick={()=>act({type:'exchange'})}>60军功 → 龙魂精华 ×5</button><p className="dragon-hint">龙谷图鉴：{d.codex.length}/9</p></div></section>;
}
