import {useState} from 'react';
import {goldSkill,goldSeals,DRAGON_FORBIDDEN} from '@/lib/goldKing';
const order=['一','二','三','四','五','六','七','八','九'];
const anchors=[[681,406],[625,647],[629,703],[512,759],[427,939],[337,1078],[405,961],[463,849],[494,602]];
const css=`.gold-forbidden-figure{position:relative;width:100%;max-width:860px;aspect-ratio:1000/1400;margin:16px auto;border:1px solid rgba(217,168,67,.25);border-radius:12px;background:radial-gradient(ellipse at center,rgba(217,168,67,.07),rgba(8,20,31,.18) 70%);overflow:hidden}.gold-forbidden-figure>svg{display:block;width:100%;height:100%}.gold-forbidden-node{position:absolute;transform:translate(-50%,-50%);width:24%;min-height:64px;padding:8px 4px;border-radius:8px;background:rgba(8,20,31,.95);border:1px solid rgba(217,168,67,.4);color:#fcd34d;font:inherit;font-size:12px;line-height:1.4;cursor:pointer}.gold-forbidden-node strong,.gold-forbidden-node small{display:block}.gold-forbidden-node small{font-size:10px;color:#94a3b8}.gold-forbidden-node[aria-pressed=true]{border-color:#fcd34d;box-shadow:0 0 12px rgba(217,168,67,.2)}.gold-forbidden-node:focus-visible{outline:2px solid #67e8f9;outline-offset:2px}.gold-forbidden-node[data-ready=true] small{color:#67e8f9}.gold-forbidden-detail{border:1px solid rgba(217,168,67,.25);border-radius:10px;padding:12px;background:rgba(8,20,31,.7)}.gold-forbidden-detail h4{color:#fcd34d;margin:0 0 8px}.gold-forbidden-failure{position:absolute;top:48%;left:30%;width:40%;font-size:12px;text-align:center;color:#94a3b8}@media(max-width:600px){.gold-forbidden-figure{aspect-ratio:1000/1400}.gold-forbidden-node{width:24%;font-size:11px;padding:6px 3px;min-height:60px}.gold-forbidden-node small{font-size:10px}.gold-forbidden-node strong{font-size:10px;white-space:nowrap}}`;
export default function GoldForbiddenFigure({player}:{player:any}){
 const [selected,setSelected]=useState(0),[failed,setFailed]=useState(false);
 const soulIndex=player.martialSoul?.name==='金龙王'?0:1,rings=(soulIndex?player.secondSoulRings:player.soulRings)||[],seals=goldSeals(player),asset=((window as any).__BASENAME__||'').replace(/\/$/,'')+'/assets/gold-dragon-spear-effects-v2.png';
 const slots=Array.from({length:9},(_,i)=>{const mapping=[0,1,2,3,4,5,-1,6,7],need=i===6?0:i<4?12:16,name=i===6?'金龙王真身':DRAGON_FORBIDDEN[mapping[i]],ready=!!rings[i]&&seals>=need,angle=(-90+i*40)*Math.PI/180;return {slot:i,name,need,ready,x:500+370*Math.cos(angle),y:700+530*Math.sin(angle),status:!rings[i]?'未获得对应魂环':seals<need?'需要'+need+'道封印':'已解锁'};});
 const active=slots[selected],skill=goldSkill(player,selected,soulIndex);
 return <><style>{css}</style><p className="dragon-hint">第一至第九魂技环绕黄金龙枪。点击节点查看当前技能和解锁条件。</p><div className="gold-forbidden-figure" data-gold-forbidden-figure><svg viewBox="0 0 1000 1400" preserveAspectRatio="none" aria-hidden="true"><image href={asset} x="270" y="400" width="460" height="690" preserveAspectRatio="xMidYMid meet" onError={()=>setFailed(true)}/>{slots.map(n=>{const [x,y]=anchors[n.slot],color=n.ready?'#d9a843':'#50657c';return <g key={n.slot} data-spear-connection={n.slot+1}><path d={`M ${n.x} ${n.y} L ${n.x+(500-n.x)*.35} ${n.y} L ${x} ${y}`} fill="none" stroke={color} strokeWidth={selected===n.slot?2:1} vectorEffect="non-scaling-stroke"/><circle cx={x} cy={y} r={selected===n.slot?7:4} fill="#08141f" stroke={selected===n.slot?'#fcd34d':color} strokeWidth="1.5" vectorEffect="non-scaling-stroke"/></g>;})}</svg>{failed&&<p className="gold-forbidden-failure">长枪暂未加载，魂技详情仍可查看。</p>}{slots.map(n=><button type="button" key={n.slot} className="gold-forbidden-node" data-spear-skill={n.slot+1} data-ready={n.ready} aria-label={'查看第'+order[n.slot]+'魂技'} aria-pressed={selected===n.slot} aria-controls="gold-forbidden-detail" style={{left:n.x/10+'%',top:n.y/14+'%'}} onClick={()=>setSelected(n.slot)}><small>第{order[n.slot]}魂技</small><strong>{n.name}</strong><small>{n.status}</small></button>)}</div><div className="gold-forbidden-detail" id="gold-forbidden-detail" aria-live="polite" data-gold-skill-detail><h4>第{order[selected]}魂技 · {active.name}</h4><p className="dragon-hint">{active.status}{active.need?' · '+active.need+'道封印后替换对应魂技':' · 第七魂技保持金龙王真身（游戏原创）'}</p><p className="dragon-muted">当前技能：{skill?.name}。{skill?.desc}</p>{!rings[selected]&&<p className="dragon-muted">仅为技能预览，需要先获得第{order[selected]}魂环才能在战斗中使用。</p>}</div></>;
}

