import GoldSealProgress from './GoldSealProgress';
import {GrowthPreview,useGrowthUpgrade,growthStyles} from './BloodlineGrowth';
import GoldForbiddenFigure from './GoldForbiddenFigure';
import {goldBloodBonuses,goldMeleeRate,goldDomainDescription} from '@/lib/goldDominance';
import GoldSealFigure from './GoldSealFigure';
import GoldBodyFigure from './GoldBodyFigure';
import {useRef,useEffect,useState} from 'react';
import {useGame} from '@/lib/gameStore';import {toast} from 'sonner';import {dragonStyles} from './DragonLegendPanel';
import {hasGoldKing,GOLD_EVOLUTIONS,goldEvolutions} from '@/lib/goldKing';
import {valleyProgress,valleyAction,valleyEnemy,bloodlineProgress,sealRequirements,evolutionRequirements} from '@/lib/dragonBloodline';
const sealStyles=`.gold-seal-art{margin:12px -16px 16px;overflow:hidden;border-top:1px solid rgba(217,168,67,.25);border-bottom:1px solid rgba(217,168,67,.25);background:#061423}.gold-seal-art img{display:block;width:100%;height:auto;aspect-ratio:1;object-fit:contain}.gold-seal-art figcaption{padding:8px 16px;color:#fcd34d;font-size:12px;text-align:center;background:rgba(8,20,31,.9)}@media(min-width:768px){.gold-seal-art{width:min(calc(100% + 32px),640px);margin:12px auto 16px;border:1px solid rgba(217,168,67,.25);border-radius:10px}}`;
export default function GoldBloodlinePanel({onBack}:{onBack:()=>void}){
 const [view,setView]=useState<'seals'|'body'|'forbidden'>('seals');
 const {player,inBattle,setPlayer,startBattle}=useGame(),gate=useRef(false);const growth=useGrowthUpgrade(player,setPlayer,inBattle);useEffect(()=>{if(!inBattle)gate.current=false;},[inBattle]);if(!player)return null;
 const d=valleyProgress(player),b=bloodlineProgress(player),req=sealRequirements(player),blood=goldBloodBonuses(player);
 function act(a:any){if(inBattle)return;const now=Date.now(),r=valleyAction(player,a,now);if(r.reason)return toast.error(r.reason);setPlayer(p=>valleyAction(p,a,now).player);toast.success(r.message);}
 function fight(){if(inBattle||gate.current||!hasGoldKing(player))return;gate.current=true;const a={type:'seal',id:crypto.randomUUID()},r=valleyAction(player,a);if(r.reason){gate.current=false;return toast.error(r.reason);}const t=r.player.dragonValley.trial;setPlayer(p=>valleyAction(p,a).player);startBattle({battleType:'challenge',locationId:'dragon-valley',enemy:valleyEnemy(t.node,t.seal),meta:{valley:{...t}}} as any);}
 if(!hasGoldKing(player))return <section className="dragon-ui" data-gold-bloodline><style>{dragonStyles+sealStyles+growthStyles}</style><button className="dragon-quiet" onClick={onBack}>← 返回</button><p className="dragon-muted">需要主修或有效次修武魂为金龙王。</p></section>;
 return <section className="dragon-ui" data-gold-bloodline><style>{dragonStyles+sealStyles+growthStyles}</style><div className="dragon-summary"><button className="dragon-quiet" onClick={onBack}>← 返回</button><span className="dragon-pill">精华 {b.essence} · 龙髓 {b.marrow} · 龙核 {b.core}</span></div><p className="dragon-hint">血脉材料可在地图中的龙谷获取。升级前可查看当前收益与下一阶收益。</p>
 {d.exploration&&<p className="dragon-warning">请先完成或结束龙谷探索，再进行封印挑战与进化。</p>}
 {d.trial&&!d.exploration&&<div className="dragon-warning">存在未结束的封印试炼<button className="dragon-quiet" disabled={inBattle} onClick={()=>act({type:'leave',id:d.trial.id})}>放弃封印试炼</button></div>}
  <div className="dragon-tabs" role="tablist" aria-label="金龙王血脉功能">{([['seals','十八道封印'],['body','金龙真身'],['forbidden','龙皇禁法']] as const).map(([id,label])=><button type="button" role="tab" id={'gold-tab-'+id} aria-controls={'gold-panel-'+id} aria-selected={view===id} key={id} className={view===id?'active':''} onClick={()=>setView(id)}>{label}</button>)}</div>
  <div role="tabpanel" id={'gold-panel-'+view} aria-labelledby={'gold-tab-'+view}>
   {view==='seals'&&<><div className="dragon-card" data-gold-prison><h3>专属领域 · 金龙镇狱领域</h3><p className="dragon-hint">{goldDomainDescription(player)}</p><p className="dragon-muted">第6、12、18道封印强化。每场一次；攻击、增益、治疗均消耗一次行动。结束、死亡或逃跑时清除。</p></div>  <div className="dragon-card" data-bloodline><h3>{b.unlocked?'金龙王血脉 · 十八道封印':'封印中的血脉'}</h3><GoldSealFigure seals={b.seals}/><GoldSealProgress player={player}/>{!b.unlocked?<p className="dragon-muted">彩蛋尚未解锁：仅持有金龙王武魂（主修或有效次修）才能解锁。</p>:<><p>已解开 {b.seals}/18 · 攻击 +{b.seals}% · 气血 +{(b.seals*1.5).toFixed(1)}%</p><p className="dragon-hint">下一封印：{req.level}级{req.next>6?' · 需要继承神位':''} · 精华 {req.essence} · 龙髓 {req.marrow} · 龙核 {req.core}。胜利才扣材料；失败不解封、不扣材料。</p><button className="dragon-primary" disabled={!!req.reason||!!d.trial||!!d.exploration||inBattle} onClick={()=>fight()}>{req.reason||'挑战第'+req.next+'道封印'}</button><p className="dragon-hint">魂环解锁魂技位置；第十二封印进化第一至第四魂技，第十六封印进化第五、第六、第八、第九魂技，第七保持金龙王真身（游戏原创）。</p> </>}</div></>}
   {view==='body'&&<><div className="dragon-card" data-gold-blood-talent><h3>专属天赋 · 金龙霸血</h3><p>霸血 {blood.points}/2000 · 永久气血 +{Math.round(blood.hp*100)}% · 攻击 +{Math.round(blood.attack*100)}%</p><progress max={2000} value={blood.points} style={{width:'100%',accentColor:'#d9a843'}}/><p className="dragon-hint">每100霸血增加1%气血与0.5%攻击，不滚雪球叠乘。转世保留；仅持有金龙王时生效。</p><p className="dragon-hint">近战附加战斗开始时永久最大气血的 {(goldMeleeRate(player)*100).toFixed(1)}%，上限为原伤害20%，仍经过防御、减伤和护盾。力量系魂技不另设成长瓶颈，原有魂环、魂力、冷却与封印要求保留。</p><p className="dragon-muted">匹配阶段的普通／精英／首领胜利获得1／3／10霸血；训练、契约、召唤、轮回之影及低阶段敌人不计。每场只结算一次。</p></div><div className="dragon-card"><h3>金龙真身</h3><p className="dragon-hint">爪部能力、身体能力、气血结构与特殊状态：随血脉封印解开逐步进化。</p></div><GoldBodyFigure levels={goldEvolutions(player)}/><div className="dragon-grid forge" data-gold-evolutions>{GOLD_EVOLUTIONS.map(e=>{const level=goldEvolutions(player)[e.id],r=evolutionRequirements(player,e.id);return <div className="dragon-card" id={'gold-evolution-'+e.id} key={e.id}><h4>{e.name} · {level}/4阶</h4><p className="dragon-hint">{level?e.stages[level-1]:'尚未进化'} → {level<4?e.stages[level]:'已达最高阶'}</p><p className="dragon-muted">{e.desc}</p><GrowthPreview player={player} king="gold" kind="body" id={e.id}/>{e.id==='state'&&<p className="dragon-muted">血龙变：消耗最大魂力15%，冷却6次行动；本次不追加普攻。</p>}{r.next<=4&&<p className="dragon-hint">下一阶：{r.seal}封印 · 精华 {r.essence} · 龙髓 {r.marrow} · 龙核 {r.core}</p>}<button className="dragon-primary" disabled={growth.busy||!!r.reason||inBattle||!!d.trial||!!d.exploration} onClick={()=>growth.upgrade('gold','body',e.id,e.name)} aria-label={'升级'+e.name}>{growth.busy?'进化提交中…':inBattle?'战斗中不可进化':d.trial||d.exploration?'请先结束龙谷试炼':r.reason||'升级进化'}</button></div>;})}</div></>}
   {view==='forbidden'&&<div className="dragon-card" data-forbidden-preview><h4>龙皇禁法</h4><GoldForbiddenFigure player={player}/></div>}
  </div>
 </section>;
}
