import GoldBodyFigure from './GoldBodyFigure';
import {useRef,useEffect,useState} from 'react';
import {useGame} from '@/lib/gameStore';import {toast} from 'sonner';import {dragonStyles} from './DragonLegendPanel';
import {hasGoldKing,GOLD_EVOLUTIONS,goldEvolutions,DRAGON_FORBIDDEN} from '@/lib/goldKing';
import {valleyProgress,valleyAction,valleyEnemy,bloodlineProgress,sealRequirements,evolutionRequirements} from '@/lib/dragonBloodline';
const sealStyles=`.gold-seal-art{margin:12px -16px 16px;overflow:hidden;border-top:1px solid rgba(217,168,67,.25);border-bottom:1px solid rgba(217,168,67,.25);background:#061423}.gold-seal-art img{display:block;width:100%;height:auto;aspect-ratio:1;object-fit:contain}.gold-seal-art figcaption{padding:8px 16px;color:#fcd34d;font-size:12px;text-align:center;background:rgba(8,20,31,.9)}@media(min-width:768px){.gold-seal-art{width:min(calc(100% + 32px),640px);margin:12px auto 16px;border:1px solid rgba(217,168,67,.25);border-radius:10px}}`;
export default function GoldBloodlinePanel({onBack}:{onBack:()=>void}){
 const [view,setView]=useState<'seals'|'body'|'forbidden'>('seals');
 const {player,inBattle,setPlayer,startBattle}=useGame(),gate=useRef(false);useEffect(()=>{if(!inBattle)gate.current=false;},[inBattle]);if(!player)return null;
 const sealArt=((window as any).__BASENAME__||'').replace(/\/$/,'')+'/assets/gold-king-eighteen-chains-v1.webp';
 const d=valleyProgress(player),b=bloodlineProgress(player),req=sealRequirements(player);
 function act(a:any){if(inBattle)return;const now=Date.now(),r=valleyAction(player,a,now);if(r.reason)return toast.error(r.reason);setPlayer(p=>valleyAction(p,a,now).player);toast.success(r.message);}
 function fight(){if(inBattle||gate.current||!hasGoldKing(player))return;gate.current=true;const a={type:'seal',id:crypto.randomUUID()},r=valleyAction(player,a);if(r.reason){gate.current=false;return toast.error(r.reason);}const t=r.player.dragonValley.trial;setPlayer(p=>valleyAction(p,a).player);startBattle({battleType:'challenge',locationId:'dragon-valley',enemy:valleyEnemy(t.node,t.seal),meta:{valley:{...t}}} as any);}
 if(!hasGoldKing(player))return <section className="dragon-ui" data-gold-bloodline><style>{dragonStyles+sealStyles}</style><button className="dragon-quiet" onClick={onBack}>← 返回</button><p className="dragon-muted">需要主修或有效次修武魂为金龙王。</p></section>;
 return <section className="dragon-ui" data-gold-bloodline><style>{dragonStyles+sealStyles}</style><div className="dragon-summary"><button className="dragon-quiet" onClick={onBack}>← 返回</button><span className="dragon-pill">精华 {b.essence} · 龙髓 {b.marrow} · 龙核 {b.core}</span></div><p className="dragon-hint">血脉材料可在地图中的龙谷获取。封印与进化进度沿用原存档。</p>
 {d.exploration&&<p className="dragon-warning">请先完成或结束龙谷探索，再进行封印挑战与进化。</p>}
 {d.trial&&!d.exploration&&<div className="dragon-warning">存在未结束的封印试炼<button className="dragon-quiet" disabled={inBattle} onClick={()=>act({type:'leave',id:d.trial.id})}>放弃封印试炼</button></div>}
  <div className="dragon-tabs" role="tablist" aria-label="金龙王血脉功能">{([['seals','十八道封印'],['body','金龙真身'],['forbidden','龙皇禁法']] as const).map(([id,label])=><button type="button" role="tab" id={'gold-tab-'+id} aria-controls={'gold-panel-'+id} aria-selected={view===id} key={id} className={view===id?'active':''} onClick={()=>setView(id)}>{label}</button>)}</div>
  <div role="tabpanel" id={'gold-panel-'+view} aria-labelledby={'gold-tab-'+view}>
   {view==='seals'&&<>  <div className="dragon-card" data-bloodline><h3>{b.unlocked?'金龙王血脉 · 十八道封印':'封印中的血脉'}</h3><figure className="gold-seal-art" data-gold-seal-art><img src={sealArt} alt="金龙被十八条锁链束缚，锁链延伸至封印展示框边缘" width={1254} height={1254} decoding="async"/><figcaption>十八道封印 · 已解开 {b.seals}/18</figcaption></figure>{!b.unlocked?<p className="dragon-muted">彩蛋尚未解锁：仅持有金龙王武魂（主修或有效次修）才能解锁。</p>:<><p>已解开 {b.seals}/18 · 攻击 +{b.seals}% · 气血 +{(b.seals*1.5).toFixed(1)}%</p><p className="dragon-hint">下一封印：{req.level}级 · 精华 {req.essence} · 龙髓 {req.marrow} · 龙核 {req.core}。胜利才扣材料；失败不解封、不扣材料。</p><button className="dragon-primary" disabled={!!req.reason||!!d.trial||!!d.exploration||inBattle} onClick={()=>fight()}>{req.reason||'挑战第'+req.next+'道封印'}</button><p className="dragon-hint">魂环解锁魂技位置；第十二封印进化第一至第四魂技，第十六封印进化第五、第六、第八、第九魂技，第七保持金龙王真身（游戏原创）。</p> </>}</div></>}
   {view==='body'&&<><div className="dragon-card"><h3>金龙真身</h3><p className="dragon-hint">爪部能力、身体能力、气血结构与特殊状态：随血脉封印解开逐步进化。</p></div><GoldBodyFigure levels={goldEvolutions(player)}/><div className="dragon-grid forge" data-gold-evolutions>{GOLD_EVOLUTIONS.map(e=>{const level=goldEvolutions(player)[e.id],r=evolutionRequirements(player,e.id);return <div className="dragon-card" id={'gold-evolution-'+e.id} key={e.id}><h4>{e.name} · {level}/4阶</h4><p className="dragon-hint">{level?e.stages[level-1]:'尚未进化'} → {level<4?e.stages[level]:'已达最高阶'}</p><p className="dragon-muted">{e.desc}</p><p className="dragon-hint">下一阶：{r.seal}封印 · 精华 {r.essence} · 龙髓 {r.marrow} · 龙核 {r.core}</p><button className="dragon-primary" disabled={!!r.reason||inBattle||!!d.trial||!!d.exploration} onClick={()=>act({type:'evolve',track:e.id})} aria-label={'升级'+e.name}>{r.reason||'升级进化'}</button></div>;})}</div></>}
   {view==='forbidden'&&<><div className="dragon-card" data-forbidden-preview><h4>龙皇禁法</h4>{[0,1,2,3,4,5,7,8].map((slot,i)=><p key={slot} className="dragon-hint">第{slot+1}魂技 · {DRAGON_FORBIDDEN[i]} · {b.seals>=(i<4?12:16)?'封印条件已满足':'需要'+(i<4?12:16)+'封印'}{(player.martialSoul?.name==='金龙王'?player.soulRings:player.secondSoulRings)?.[slot]?'':' · 仍需对应魂环'}</p>)}</div></>}
  </div>
 </section>;
}
