import {useState} from 'react';
import {toast} from 'sonner';
import {useGame} from '@/lib/gameStore';
import {dragonStyles} from './DragonLegendPanel';
import {hasSilverKing,SILVER_ELEMENTS,SILVER_BODY,silverRanks,silverSkill,silverRequirement,silverUpgrade,silverDomain} from '@/lib/silverKing';
const css=`.silver-figure{position:relative;max-width:860px;margin:16px auto;aspect-ratio:1000/1400;border:1px solid #23465a;border-radius:12px;overflow:hidden;background:radial-gradient(ellipse,#15334855,#08141f44 70%)}.silver-figure>svg{width:100%;height:100%;display:block}.silver-node{position:absolute;transform:translate(-50%,-50%);width:24%;min-height:60px;padding:8px 3px;background:#08141ff5;border:1px solid #47697a;border-radius:8px;color:#b8edff;font:inherit;font-size:12px;cursor:pointer}.silver-node strong,.silver-node small{display:block}.silver-node small{font-size:10px;color:#94a3b8}.silver-node[aria-pressed=true]{border-color:#67e8f9;box-shadow:0 0 10px #67e8f922}.silver-node:focus-visible{outline:2px solid #67e8f9}.silver-detail{padding:12px;border:1px solid #23465a;border-radius:10px;background:#08141faa}.silver-failure{position:absolute;left:30%;top:45%;width:40%;color:#94a3b8;text-align:center;font-size:12px}@media(max-width:600px){.silver-node{font-size:11px;min-height:56px;padding:5px 2px}}`;
const names=['一','二','三','四','五','六','七','八','九'];
function SilverFigure({player,view,selected,onSelect}:{player:any;view:string;selected:number;onSelect:(n:number)=>void}){
 const [failed,setFailed]=useState(false),r=silverRanks(player),soulIndex=player.martialSoul?.name==='银龙王'?0:1,rings=(soulIndex?player.secondSoulRings:player.soulRings)||[];
 const nodes=view==='elements'?SILVER_ELEMENTS.map((e,i)=>({id:e,label:e+'元素',status:r.elements[e]+'/4阶',ready:r.elements[e]>0,ax:450+(i%2)*110,ay:370+i*105})):view==='body'?SILVER_BODY.map((e,i)=>({id:e.id,label:e.name,status:r.body[e.id]+'/4阶',ready:r.body[e.id]>0,ax:[470,450,480,635][i],ay:[790,460,690,590][i]})):Array.from({length:9},(_,i)=>({id:String(i),label:silverSkill(player,i,soulIndex)?.name,status:!!rings[i]?'已解锁':'未获得魂环',ready:!!rings[i],ax:660-i*37,ay:440+i*66}));
 const positions=nodes.map((n,i)=>{if(view==='body')return {...n,x:i%2?855:145,y:i<2?470:1000};const a=(-90+i*360/nodes.length)*Math.PI/180;return {...n,x:500+370*Math.cos(a),y:700+530*Math.sin(a)};});
 const asset=((window as any).__BASENAME__||'').replace(/\/$/,'')+'/assets/'+(view==='elements'?'silver-dragon-elements.png':view==='body'?'silver-dragon-body.png':'silver-dragon-spear.png');
 return <div className="silver-figure" data-silver-figure={view}><svg viewBox="0 0 1000 1400" aria-hidden="true"><image href={asset} x={view==='body'?235:250} y={view==='body'?230:300} width={view==='body'?530:500} height={view==='body'?980:850} preserveAspectRatio="xMidYMid meet" onError={()=>setFailed(true)}/>{positions.map((n,i)=><g key={n.id} data-silver-connection={n.id}><path d={`M ${n.x} ${n.y} L ${n.x+(500-n.x)*.35} ${n.y} L ${n.ax} ${n.ay}`} fill="none" stroke={selected===i?'#67e8f9':n.ready?'#8ebacb':'#476071'} strokeWidth={selected===i?2:1} vectorEffect="non-scaling-stroke"/><circle cx={n.ax} cy={n.ay} r={selected===i?6:4} fill="#08141f" stroke="#b8edff"/></g>)}</svg>{failed&&<div className="silver-failure">图片暂未加载，功能仍可使用。</div>}{positions.map((n,i)=><button type="button" key={n.id} className="silver-node" style={{left:n.x/10+'%',top:n.y/14+'%'}} aria-pressed={selected===i} aria-controls={'silver-detail-'+view} onClick={()=>onSelect(i)}><small>{view==='skills'?'第'+names[i]+'魂技':''}</small><strong>{n.label}</strong><small>{n.status}</small></button>)}</div>;
}
export default function SilverBloodlinePanel({onBack}:{onBack:()=>void}){
 const {player,setPlayer,inBattle}=useGame(),[view,setView]=useState('elements'),[selected,setSelected]=useState(0);if(!player)return null;
 const r=silverRanks(player),d=silverDomain(player),bag=player.dragonBloodline||{};
 function upgrade(kind:'elements'|'body',id:string){if(inBattle)return;const v=silverUpgrade(player,kind,id);if(v.reason)return toast.error(v.reason);setPlayer(p=>silverUpgrade(p,kind,id).player);toast.success('进化完成');}
 const kind=view==='elements'?'elements':'body',id=view==='elements'?SILVER_ELEMENTS[selected]:SILVER_BODY[selected]?.id,req=view==='skills'?null:silverRequirement(player,kind,id),soulIndex=player.martialSoul?.name==='银龙王'?0:1,skill=view==='skills'?silverSkill(player,selected,soulIndex):null;
 return <section className="dragon-ui" data-silver-bloodline><style>{dragonStyles+css}</style><div className="dragon-summary"><button className="dragon-quiet" onClick={onBack}>← 返回</button><span className="dragon-pill">精华 {bag.essence||0} · 龙髓 {bag.marrow||0} · 龙核 {bag.core||0}</span></div>{!hasSilverKing(player)?<p className="dragon-muted">需要主修或有效次修武魂为银龙王。</p>:<><p className="dragon-hint">血脉材料在龙谷获取；全属性共鸣每类只计算一次；血脉仍培养七种元素，魂环与魂骨保留自身属性。</p><div className="dragon-tabs" role="tablist" aria-label="银龙王血脉功能">{[['elements','元素掌控'],['body','银龙真身'],['skills','银龙神技']].map(([v,label])=><button key={v} role="tab" aria-selected={view===v} aria-controls={'silver-panel-'+v} className={view===v?'active':''} onClick={()=>{setView(v);setSelected(0);}}>{label}</button>)}</div><div role="tabpanel" id={'silver-panel-'+view}>
 {view==='elements'&&<div className="dragon-card"><h3>银龙元素领域</h3><p className="dragon-hint">掌控3／5／7种元素后，入战自动展开3次行动：魂技伤害+10／15／20%，消耗降低5／8／10%。当前：{d?`伤害+${d.damage*100}%，消耗-${d.cost*100}%`:'尚未解锁'}。</p><p className="dragon-muted">可与金龙镇狱领域同时展开，独立计时；切换武魂不会重置。</p></div>}
 {view==='body'&&<div className="dragon-card"><h3>元素感悟 · {r.insight.points}/2000</h3><progress max={2000} value={r.insight.points} style={{width:'100%',accentColor:'#67e8f9'}}/><p className="dragon-hint">每100点：精神+1%、魂力上限+0.5%。匹配阶段普通／精英／首领胜利+1／3／10，排除低阶、训练、召唤与轮回之影。转世保留感悟，元素与真身进化重置；仅持有银龙王时生效。</p></div>}
 <SilverFigure key={view} player={player} view={view} selected={selected} onSelect={setSelected}/><div className="silver-detail" id={'silver-detail-'+view} aria-live="polite">{view==='skills'?<><h3>第{names[selected]}魂技 · {skill?.name}</h3><p className="dragon-hint">{skill?.desc}</p><p className="dragon-muted">需要对应魂环；第七魂技通过战斗中的武魂真身开关释放。</p></>:<><h3>{view==='elements'?id+'元素':SILVER_BODY[selected].name} · {req?.rank}/4阶</h3><p className="dragon-hint">{view==='body'?SILVER_BODY[selected].desc:'每种元素每阶银龙王魂技伤害+0.5%，总上限14%；已掌控种类用于强化领域。'}</p><p className="dragon-muted">下一阶：{req?.level}级 · 精华{req?.essence} · 龙髓{req?.marrow} · 龙核{req?.core}。第三、第四阶需要继承神位。</p><button className="dragon-primary" disabled={inBattle||!!req?.reason} onClick={()=>upgrade(kind,id)}>{inBattle?'战斗中不可进化':req?.reason||'升级进化'}</button></>}</div></div></>}</section>;
}
