import {useState} from 'react';
import {useGame} from '@/lib/gameStore';
import {hasTwinDragon,readTwin,twinActiveStage,twinBonuses,twinConditions,twinUpgrade,TWIN_STAGES,TWIN_SKILLS} from '@/lib/twinDragon';
import {goldDomainDescription} from '@/lib/goldDominance';
import {silverDomain} from '@/lib/silverKing';
import {toast} from 'sonner';
export default function TwinDragonPanel({onBack}:{onBack:()=>void}){
 const {player,setPlayer,inBattle}=useGame(),[tab,setTab]=useState('growth'),[selected,setSelected]=useState(0);
 const v=readTwin(player?.twinResonance),a=twinActiveStage(player),bonus=twinBonuses(player),r=TWIN_STAGES[selected],bag=player?.dragonBloodline||{},sd=silverDomain(player);
 const box='rounded-xl border border-cyan-500/25 bg-card/40 p-4 space-y-2',pct=(n:number)=>(n*100).toFixed(0)+'%';
 if(!hasTwinDragon(player)||!player||player.level<60)return <div className="p-4"><button onClick={onBack}>返回</button><p className="mt-4">60级且有效双生武魂分别为金龙王、银龙王时开启金银共鸣。</p></div>;
 return <div className="p-4 space-y-4 max-w-3xl mx-auto" data-twin-dragon-panel><header><button className="text-cyan-300" onClick={onBack}>← 返回</button><h2 className="text-xl font-semibold text-cyan-200 mt-3">金银共鸣</h2><p className="text-sm text-muted-foreground">已培养{v.stage}/5阶 · 当前生效{a}/5阶 · 游戏原创联动</p></header>
 <nav className="flex gap-2">{[['growth','共鸣成长'],['skills','联动能力'],['domains','双领域']].map(([id,name])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id)} className={'flex-1 p-2 rounded-lg border text-sm '+(tab===id?'border-cyan-400 text-cyan-200 bg-cyan-950/40':'border-border text-muted-foreground')}>{name}</button>)}</nav>
 <div className={box}><p>共鸣值 {v.points}/2,000</p><div role="progressbar" aria-label="金银共鸣进度" aria-valuenow={v.points} aria-valuemin={0} aria-valuemax={2000} style={{height:6,borderRadius:99,background:"rgba(34,211,238,.12)",overflow:"hidden"}}><div style={{height:"100%",width:(v.points/20)+"%",background:"#22d3ee"}}/></div><p className="text-xs text-muted-foreground">合格普通／精英／首领胜利+1／3／10，不扣共鸣值；同场一次。训练、召唤、轮回之影、封印试炼和低难度不计入。</p><p className="text-sm">当前：气血、防御+{pct(bonus.hp)} · 攻击、精神+{pct(bonus.attack)} · 双龙攻击技能+{pct(bonus.damage)}</p>{v.stage>a&&<p className="text-amber-300 text-sm">培养记录已保留；本世条件不足，高阶段效果暂停。</p>}</div>
 {tab==='growth'&&<><div className="grid grid-cols-5 gap-1">{TWIN_STAGES.map((s,i)=><button key={s.name} aria-pressed={selected===i} className={'text-xs rounded-lg border p-2 '+(selected===i?'border-cyan-400 text-cyan-200':'border-border')} onClick={()=>setSelected(i)}>{i+1}阶<br/>{s.name}</button>)}</div><div className={box}><h3>{selected+1}阶 · {r.name}</h3>{(twinConditions(player,selected+1) as any[]).map(c=><p key={c.label} className={'text-sm '+(c.ok?'text-cyan-200':'text-muted-foreground')}>{c.ok?'✓':'○'} {c.label}</p>)}<p>共鸣值 {v.points}/{r.points}（不扣除）</p><p className="text-sm">消耗：精华 {bag.essence||0}/{r.essence} · 龙髓 {bag.marrow||0}/{r.marrow} · 龙核 {bag.core||0}/{r.core}</p><p className="text-sm">本阶累计：气血、防御+{selected+1}% · 攻击、精神+{selected}% · 技能伤害+{selected+1}% · 双域期间再+{selected+1}%</p>{selected>=3&&<p className="text-sm">双领域各延长1次行动，最多4次。</p>}<button className="w-full rounded-lg p-3 border border-cyan-500 text-cyan-200 disabled:opacity-40" disabled={inBattle||selected!==v.stage||v.stage>=5} onClick={()=>{if(inBattle)return;const expected=v.stage,result=twinUpgrade(player,expected);if(result.reason){toast.error(result.reason);return;}setPlayer(p=>twinUpgrade(p,expected).player);toast.success('共鸣升级：'+r.name);}}> {selected<v.stage?'已培养':selected>v.stage?'先完成上一阶':'升级到本阶'}</button></div></>}
 {tab==='skills'&&TWIN_SKILLS.map(s=><div className={box} key={s.id}><h3>{s.name} · {a>=s.stage?'已解锁':s.stage+'阶解锁'}</h3><p className="text-sm">{s.desc}</p><p className="text-xs text-muted-foreground">游戏原创 · 消耗最大魂力{pct(s.cost)} · {s.cooldown?'冷却'+s.cooldown+'次行动':'每场一次'} · 占用一次行动，不追加普攻</p></div>)}
 {tab==='skills'&&<p className="text-xs text-muted-foreground">D为两武魂已获第一至第六攻击魂技最高基础伤害的平均值，含目标防御，不含暴击、领域及技能附带效果；缺少一方攻击魂技时不可释放。组合技能不享受银龙减耗。</p>}
 {tab==='domains'&&<><div className={box}><h3>金龙镇狱领域</h3><p className="text-sm">{goldDomainDescription(player).replace('3次',a>=4?'4次':'3次')}</p></div><div className={box}><h3>银龙元素领域</h3><p className="text-sm">{sd?'技能伤害+'+pct(sd.damage)+'，魂力消耗-'+pct(sd.cost):'至少培养3种元素后解锁'}。</p></div><div className={box}><p>双领域共同有效时，额外伤害+{pct(bonus.damage)}。任一结束立即取消联动收益。</p><p className="text-sm">当前持续上限：{a>=4?4:3}次玩家行动。每场一次，跳过行动也递减，刷新不重置。</p><p className="text-xs text-muted-foreground">共鸣伤害合计最多10%；总破甲60%；总护盾6%；不会取消金龙领域易伤。</p></div></>}
 </div>;
}
